## 2D Numpy in Python

##### Initializing 2d ndarray

In [10]:
#Creating a ndarray from a List
import numpy as np

arr_list = [[1,2,3],[8,9,0],[-2,-4,-6]]
a = np.array(arr_list)
a

array([[ 1,  2,  3],
       [ 8,  9,  0],
       [-2, -4, -6]])

In [4]:
type(a)

numpy.ndarray

In [5]:
#Dimension
a.ndim

2

In [ ]:
#Shape
a.shape

(3, 3)

In [7]:
#Size
a.size

9

In [11]:
print(a)
#Access the element in 2nd-row, 3rd column
a[1,2]

[[ 1  2  3]
 [ 8  9  0]
 [-2 -4 -6]]


np.int64(0)

In [12]:
# Access the element on the third row and third column
a[2][2]

np.int64(-6)

##### Slicing

In [14]:
a  #Ref ndarray

array([[ 1,  2,  3],
       [ 8,  9,  0],
       [-2, -4, -6]])

In [13]:
# Access the element on the first row and first and second columns
a[0,0:2]

array([1, 2])

In [16]:
# Access the element on the first and second rows and third column
a[0:2,2]

array([3, 0])

#### Basic Operations

**Adding** 2D Arrays:

In [20]:
x = np.array([[1, 0], [0, 1]]) 
x 


array([[1, 0],
       [0, 1]])

In [21]:
y = np.array([[2, 1], [1, 2]])
y

array([[2, 1],
       [1, 2]])

In [22]:
#Adding
x + y

array([[3, 1],
       [1, 3]])

**Multiply** two arrays:

In [23]:
x * y

array([[2, 0],
       [0, 2]])

**Multiply** by Scalar:

In [24]:
x

array([[1, 0],
       [0, 1]])

In [26]:
#Multiply by scalar
x * 2

array([[2, 0],
       [0, 2]])

#### Matrix multiplication on 2 Arrays

In [27]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [28]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [29]:
#Using dot function to multiply 2 arrays
res = np.dot(A, B)
res

array([[0, 2],
       [0, 2]])

In [30]:
# Calculate the sine of Z
np.sin(res)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [ ]:
# Get Transpose of matrix 'A'
print(A)
A.T   #<<transpose

[[0 1 1]
 [1 0 1]]


array([[0, 1],
       [1, 0],
       [1, 1]])

--end--